### ISSUE TITLE
[1.1.6] Lecture/Tutorial Research

### ISSUE THREAD

**Issue by BenjaminTham-SIT** [BenjaminTham-SIT/INF2001_P4-5#18]
### About:
Valuable materials have been taught in the lectures and tutorials. Hence, the team decided to take the earliest possible timing to catch up ahead of weeks worth of lectures to proceed with the project.
____________________________________________________________________________________________________________________________
### Goals:
- understand lecture 1: software development cycle
- understand lecture 2: requirements engineering
- understand lecture 3: project management
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] finish up lecture 1
- [x] finish up lecture 2
- [x] finish up lecture 3

____________________________________________________________________________________________________________________________
### Allocated Time:
4 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
6/9 - 9/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [x] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by BenjaminTham-SIT** [comment]
### Work Done:
Everyone finished reading up on lectures 1-3.
____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)


____________________________________________________________________________________________________________________________
### Start Date - End Date:
6/9 - 9/9
