### ISSUE TITLE
[1.1.2] Project Domain Research

### ISSUE THREAD

**Issue by BenjaminTham-SIT** [BenjaminTham-SIT/INF2001_P4-5#20]
### About:
Due to the project vagueness, more research about this project needs to be done. This is to ensure a more streamlined approach to tackle this project. 
Research materials for the project can be gathered by asking the profs about this matter, clarifying the aim, objectives and goals for this project. This also stems from gathering previous/past reports from seniors and do deep research and analysis to produce the best approach for  this project. 
____________________________________________________________________________________________________________________________
### Goals:
- every member of the team understands the project clearly
- every member of the team knows the objectives and goals for the project 
- every member clearly identifies the project expectations from previous reports. 
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] ask prof for more detail
- [ ] ask seniors for more detail
- [x] gather seniors past reports
- [x] analyze seniors past reports
- [ ] gain a good understanding of the project 
- [ ] set project expectations with the team 
- [ ] develop a project goal and objective

____________________________________________________________________________________________________________________________
### Allocated Time:
1hr per day

____________________________________________________________________________________________________________________________
### Start date - End Date:
29/8 - 30/8

____________________________________________________________________________________________________________________________
### Person-in-charge:

- [x] Benjamin
- [x] Claire
- [x] Claris
- [x] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [ ] High Priority 
- [ ] Medium Priority 
- [x] Low Priority

____________________________________________________________________________________________________________________________
### Notes:
Due to commitments and other higher priority tasks, this task have been pushed back multiple times resulting in us passing its deadline.

**Comment by BenjaminTham-SIT** [comment]
### Work Done:
- gathered multiple reports 
- gathered feedbacks from professors
- queried with the professors on certain doubts 
____________________________________________________________________________________________________________________________
### Repository Commit status:
no commits
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
overdue task
____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
[29/8/2023] - asked prof to clear certain doubts
[30/8/2023] - gathered one report from ict2201 class

____________________________________________________________________________________________________________________________
### Start Date - End Date:
29/8 - overdue
