### ISSUE TITLE
[1.1.3] Project Approach Planning

### ISSUE THREAD

**Issue by BenjaminTham-SIT** [BenjaminTham-SIT/INF2001_P4-5#65]
### About:
An approach towards this project needs to be carefully planned before proceeding. This approach includes what software development cycle the team is planning to use, the main task delegations and project expectations. This is so everyone has a clear direction of what to aim for.
____________________________________________________________________________________________________________________________
### Goals:

- Everyone on the team is on board with the same SDLC
- Everyone accepts their individual passive tasks delegated to them  
- Everyone produces a project expectation 

____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] Decide on a software development cycle 

- [x] Decide on individual task delegation

1. Claris
2. Claire
3. Megan
4. Alyssa
5. Benjamin

- [x] Affirm a project expectation

____________________________________________________________________________________________________________________________
### Allocated Time:
 1 day
____________________________________________________________________________________________________________________________
### Start date - End Date:
5/9 - 5/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [x] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [ ] High Priority 
- [x] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by BenjaminTham-SIT** [comment]
### Work Done:
- hosted a group meeting after class to discuss SDLC approach
- decided on task delegations
- discussed project expectations
____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
[5/9] - SDLC approach decided
[5/9] - Tasks delegated
[5/9] - meeting concluded

____________________________________________________________________________________________________________________________
### Start Date - End Date:
5/9 - 5/9
