### ISSUE TITLE
[1.5.2] Work breakdown structure update

### ISSUE THREAD

**Issue by BenjaminTham-SIT** [BenjaminTham-SIT/INF2001_P4-5#68]
### About:
After the completion of requirements gathering, we had to step back and do some general house keeping on the work breakdown structure WBS. Hence, we have to reupdate and reorganize certain activities and tasks.
____________________________________________________________________________________________________________________________
### Goals:
- align the activities and task properly 
- update wbs to most recent tasks done
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] finish phase 1: milestone 1
- [x] finish phase 2: milestone 2
- [x] finish phase 3: milestone 3

____________________________________________________________________________________________________________________________
### Allocated Time:
 3 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
19/9-21/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [x] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [x] In Progress
- [ ] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/80028e8d-59e0-4471-9a9c-a8f1156f0864)

**Comment by BenjaminTham-SIT** [comment]
### Work Done:
completed milestone 1 wbs
completed milestone 2 wbs
completed milestone 3 wbs
____________________________________________________________________________________________________________________________
### Repository Commit status:
uploaded to repo
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
[19/9/2023] - finished milestone 1 wbs
[20/9/2023] - finished milestone 2 wbs

____________________________________________________________________________________________________________________________
### Start Date - End Date:
19/9 - 21/9

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/7d405b3a-8784-4573-8b6c-08a80ef1dcba)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/d3335d36-6422-4bb9-aa3c-8ba7c27f9be3)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/7fa138cd-2a95-48e2-ae8b-0cb3f0951715)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/24f02dae-0a6f-4317-80e2-fed0143e7ba3)
