### ISSUE TITLE
[1.6.4] M1 Report Draft 1: Project Estimation

### ISSUE THREAD

**Issue by claris0911** [BenjaminTham-SIT/INF2001_P4-5#71]
### About:
M1 report project estimation and plan describes the resources required and overall time estimated for the project. 
____________________________________________________________________________________________________________________________
### Goals:
- produce and calculate correct estimations 
- produce complexity factors
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] software estimation 
- [x] unadjusted use case weight
- [x] unadjusted actor weight
- [x] technical complexity factor
- [x] environmental complexity factor 
- [x] use case points calculation 
- [x] effort estimation 
- [x] duration estimation 
- [x] resource estimation 
- [x] size estimation 
- [x] gantt chart 
- [x] wbs

____________________________________________________________________________________________________________________________
### Allocated Time:
4 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
20/9 - 23/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [x] Claris
- [ ] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by claris0911** [comment]
### Work Done:
Completed unadjusted use case weight. Can also be found on the drive Calculations.xlsx sheets

<html>
<body>
<google-sheets-html-origin>

Use Case Number | Use Case Name | Total Transactions/Usecase (original) | Step per transaction | Complexity of a  Usecase (Don't edit this)
-- | -- | -- | -- | --
1 | Update User | 4 | (1-3)(4) (5-7)(3a1) | 10
2 | Create User | 4 | (1-3)(4-5)(3a1)(3b1) | 10
3 | Delete User | 4 | (1-2)(3-4)(3a)(3b) | 10
4 | Allocate Jobs to Employee | 4 | (1-3)(4-5)(6-7)(6a) | 10
5 | Create Job | 6 | (1-4)(5-6)(7-8)(9)(10)(8a1) | 10
6 | View Employee Availability | 3 | (1-3)(4)(4a1) | 5
7 | Export Workload | 10 | (1-4)(5-6)(7)(8)(1-3)(4-5)(6)(5a1)(8a1) | 15
8 | View Employee Workload | 2 | (1-3)(4) | 5
9 | Add to Standby List | 4 | (1-3)(4-5)(3a1) | 10
10 | Edit Existing Job | 7 | (1-3)(4-5)(6-7)(8)(9)(6a)(8a) | 10
11 | Cancel Job | 8 | (1-3)(4-5)(6)(1-3)(4-5)(6)(5a1)(6a2) | 15
12 | View Allocated Job | 2 | (1-3)(4-5) | 5
13 | Edit Availability | 3 | (1-3)(4-5)(3a1) | 5
14 | Add Availability | 4 | (1-3)(4-6)(7)(3a1) | 10
15 | Reject Job | 6 | (1-2)(3-4)(5-6)(7-8)(3a1)(6a1) | 10
16 | Indicate Job Preference | 3 | (1-3)(4-5)(4a1) | 5
  |   |   |   |  
  |   |   |   |  
  |   |   | Total unadjusted use case weight | 145
  |   |   | Adding actors weight | 158


</body>
</html>
____________________________________________________________________________________________________________________________
### Repository Commit status:
no commits
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
23/9
____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
23/9/2023 - Completed unadjusted use case weight

____________________________________________________________________________________________________________________________
### Start Date - End Date:
20/9 - 23/9

**Comment by claris0911** [comment]
### Work Done:
Completed technical complexity factors. Can also be found on the drive Calculation.xlsx sheets

<html>
<body>
<google-sheets-html-origin>
Factor | Description | Weight | Degree of Influence | Product
-- | -- | -- | -- | --
T1 | Distributed system | 2 | 4 | 8
T2 | Response time/performance objectives | 1 | 3 | 3
T3 | End-user efficiency | 1 | 5 | 5
T4 | Internal processing complexity | 1 | 4 | 4
T5 | Code reusability | 1 | 5 | 5
T6 | Easy to install | 0.5 | 2 | 1
T7 | Easy to use | 0.5 | 5 | 2.5
T8 | Portability to other platforms | 2 | 1 | 2
T9 | System maintenance | 1 | 3 | 3
T10 | Concurrent/parallel processing | 1 | 4 | 4
T11 | Security features | 1 | 3 | 3
T12 | Access for third parties | 1 | 2 | 2
T13 | End user training | 1 | 1 | 1
  |   |   | Total | 43.5


</body>
</html>

____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
23/9/2023 - Completed technical complexity factors

____________________________________________________________________________________________________________________________
### Start Date - End Date:
20/9 - 23/9

**Comment by claris0911** [comment]
### Work Done:
completed calculation of UCP

UCP = (UUCW + UAW) * TCF * ECF
UCP= (145 + 13) * 1.035 * 0.695
UCP = 113.65 (5s.f.)

____________________________________________________________________________________________________________________________
### Repository Commit status:
No commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
23/09/2023 - Completed calculation of UCP 

____________________________________________________________________________________________________________________________
### Start Date - End Date:
21/9 - 23/9

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/cc6adbad-8140-4f7b-913a-d8c32e0ab6ae)

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/7dacf895-3c8e-49d8-8dd7-b74c7ae79466)

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/a1e5ef37-48bd-49c7-80c1-f9e2e8a7394c)

**Comment by BenjaminTham-SIT** [comment]
**Effort Estimation**
Optimistic Total Hours: 113.65 UCP  15 hours = 1704.75 Total Hours
Pessimistic Total Hours: 113.65 UCP  30 hours = 3409.5 Total Hours

Optimistic Total Hours per developer: 1704.75 Total Hours / 5 = 340.95 Hours
Pessimistic Total Hours per developer: 3409.5 Total Hours / 5 = 681.9 Hours


Optimistic hours for one developer per week: 340.95 Hours  8 weeks = 42.61875 Hours
Pessimistic hours for one developer per week: 681.9 Hours  8 weeks = 85.2375 Hours


**Duration Estimation**
 Mean = [Optimistic Duration + (4  Most Likely Duration) +Pessimistic Duration] / 6
Mean = [1704.75 + (4 625.075) + 3409.5]/6 =1269.09167 hours 


Standard Deviation = Pessimistic Duration - Optimistic Duration 6
Standard Deviation = [3409.5 - 1704.75]/6 = 284.125

Variance = Standard Deviation2
Variance = 284.1252 * 284.1252 = 80727.0156

**Comment by BenjaminTham-SIT** [comment]
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/26a1c87a-f6ac-4215-98a5-9abce97d657e)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/18529df7-d61c-424e-a2a2-5f760e300af7)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/8eb65e2b-00b7-49bd-bfe5-583b9e7a810f)
![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/118095382/60a4d94a-b87f-49ca-92dc-5465102f7ba5)

**Comment by Claire1202** [comment]
Work Done: Completed environmental  complexity factors. Can also be found on the drive Calculation.xlsx sheets




![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/115334872/c4653d28-3da0-4020-85c8-ad6b0a75fd5d)

**Comment by Claire1202** [comment]
Work Done:
Completed actor weight. Can also be found on the drive Calculations.xlsx sheets


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/115334872/64345d9a-7f6c-4828-9847-4468ddfd1ed8)

**Comment by Claire1202** [comment]
Work Done:
completed calculation of UCP

UCP = (UUCW + UAW) * TCF * ECF
UCP= (145 + 13) * 1.035 * 0.695
UCP = 113.65 (5s.f.)
