### ISSUE TITLE
[1.6.2] M1 Report Draft 1: Overall Description

### ISSUE THREAD

**Issue by itsalys** [BenjaminTham-SIT/INF2001_P4-5#72]
### About:
M1 report overall description describes the context and origin of the product being specified. This section includes system architecture diagram, a proposed techstack, product functionality, assumptions and dependencies. 
____________________________________________________________________________________________________________________________
### Goals:
- complete overall description 
- produce a tech stack proposal 
- produce a system architecture diagram
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] introduction to overall description 
- [x] product overview
- [x] system architecture diagram
- [x] product functionality 
- [x] assumptions and dependencies 

____________________________________________________________________________________________________________________________
### Allocated Time:
4 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
20/9 - 23/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [x] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [x] In Progress
- [ ] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by itsalys** [comment]
### Work Done:
Completed Product Functionality, Assumptions and Dependencies

**Product Functionality**

PF1: The product shall be a responsive web-based application accessible through any device and screen resolution.
PF2: The product shall allow employees to view their weekly jobs and overall monthly workload on the employee landing page.
PF3: The product shall allow employees to manage their job availability and preferences.
PF4: The product shall allow employees to reject jobs allocated and cancel jobs in case of emergency.
PF6: The product shall allow managers to configure specifications within the product. This includes the start and deadline for employees to submit availability and preference, the employee's job rejection submission deadline, the employee's job cancellation submission deadline, and the manager's job cancellation submission deadline.
PF7: The product shall allow the manager to view the workload and jobs of employees on the manager landing page.
PF8: The product shall allow the manager to create, modify, or cancel jobs. 
PF9: The product shall allow managers to allocate employees to a job based on their availability and preferences. 
PF10: The system shall not allow the manager to publish all the job allocations if 90% of the jobs have not been allocated.
PF11: The product shall maintain a standby list to allow managers to allocate new employees efficiently in case of rejection or cancellation. 
PF12: The product shall allow managers to allocate new make-up jobs for the employees based on their availability and preferences. 
PF13: The product shall be able to track the employees' workload, such as keeping track of the employees with the lowest working hours and the employees exceeding 40 hours.
PF14: The product shall be able to track how often preferences are fulfilled. 
PF15: The product shall allow the admin to create, delete, and modify all user accounts.
PF16: The product shall be able to export the workload into a CSV file.

**Technical Assumptions**

Servers, networking components, and cloud services, will be available to support the system.
All users have stable internet connection.
System will assume the employee accepts the job by default, if there is no rejection.
System will assume the employee is available throughout all business hours by default, if availability is not submitted for the respective days.
System will assume the employee has no preferred dates, times, or instruments, if preference is not submitted for the respective days.


**Non-Technical Assumptions**

Each music school branch will have its own independent workload management system.
Users are to adhere to the security policies and requirements for strong passwords when logging into the system.
Training and support is provided for employees on how to utilize the system.


**Dependencies**

The system's successful deployment and integration depends on the acceptance and cooperation of the users who will be utilising the system.

____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit

____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
22/07/2023- Completed Product Functionality, Assumptions and Dependencies


____________________________________________________________________________________________________________________________
### Start Date - End Date:
20/9 - 23/9

**Comment by itsalys** [comment]
### Work Done:
Completed Introduction, Product Overview and System Diagram



![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/69067945/a4196a34-c6be-47fb-8a07-e85027617fd2)



____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit

____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
22/07/2023 - Completed Product Functionality, Assumptions and Dependencies
22/07/2023 - Completed Introduction, Product Overview and System Diagram


____________________________________________________________________________________________________________________________
### Start Date - End Date:
20/9 - 23/9
