### ISSUE TITLE
[1.6.3] M1 Report Draft 1: Specific Requirements

### ISSUE THREAD

**Issue by itsalys** [BenjaminTham-SIT/INF2001_P4-5#73]
### About:
M1 report specific requirements describes the logical characteristics of each interface between product and the users. 
____________________________________________________________________________________________________________________________
### Goals:
- produce user interface requirements
- produce concise requirements
- produce a use case model

____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] user interface requirements
- [x] functional requirements 
- [x] use case model
- [x] non functional requirements 
- [x] accessibility requirements
- [x] performance requirements
- [x] safety and security requirements 
- [x] other requirements 

____________________________________________________________________________________________________________________________
### Allocated Time:
 4 days 
____________________________________________________________________________________________________________________________
### Start date - End Date:
20/9 - 23/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [x] Alyssa
- [ ] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [x] In Progress
- [ ] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by claris0911** [comment]
### Work Done:
Completed use case model/diagram

[INF2001 Use Case Diagram - Draft 4.pdf](https://github.com/BenjaminTham-SIT/INF2001_P4-5/files/12705820/INF2001.Use.Case.Diagram.-.Draft.4.pdf)
____________________________________________________________________________________________________________________________
### Repository Commit status:
No commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
23/09/2023 - Completed use case model 

____________________________________________________________________________________________________________________________
### Start Date - End Date:
20/9 - 23/9

**Comment by itsalys** [comment]
### Work Done:

Completed Accessibility and User Experience sections of the User Interface Requirements

**Accessibility**

- The system adheres to accessibility standards and guidelines to ensure the UI is usable for individuals with disabilities.
- The UI must provide multilingual support, allowing users to select their preferred language and locale, ensuring a localized experience in terms of date formats, currency symbols, and language content throughout the application.

**User Experience** 

- Maintain uniform button styles, font choices, color scheme, and spacing across all screens and interactions.
- Maintain a cohesive user experience by adhering to a consistent design language and navigation structure across all platform versions.
-  The UI shall adapt seamlessly across various screen sizes.
- The UI shall provide visual cues for input validation, i.e. success and error messages. 
- A confirmation dialog will be displayed for critical actions, such as job rejection, to prevent accidental actions and provide users with a final confirmation before proceeding.
- A notification will be sent to affected users following critical actions, such as job rejections and cancellations. 

____________________________________________________________________________________________________________________________
### Repository Commit status:
no Commit

____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
22/09/2023 - Completed Functional & Non-functional (Accessibility, Performance, Safety and Security) and Others Requirements
23/09/2023 - Completed use case model
23/09/2023 - Completed Completed Accessibility and User Experience sections of the User Interface Requirements

**Comment by Claire1202** [comment]
Completed use case descriptions

[Use Case Descriptions Finalised.pdf](https://github.com/BenjaminTham-SIT/INF2001_P4-5/files/12706271/Use.Case.Descriptions.Finalised.pdf)

**Comment by 2202528** [comment]
### Work Done:

Completed Design and Branding and User Interface sections of User Interface Requirements

**Design and Branding**


Company Logo:

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/64298a26-1c92-4a03-b291-01fea327f297)


Colour Palette:

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/9cd20bd5-baf5-43c2-ae1a-e4c6511837ee)


Font Style and Size:

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/0ea1330b-a66f-4291-8558-e6256ad96671)


**User Interface Requirements**


I created 3 wireframes, representing the Manager Dashboard, the Employee Dashboard and for the Employee Job Allocation page.

Manager Dashboard - With Annotations



![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/fd6f433a-8f89-4d6c-b277-10dbf58f16be)



Manager Dashboard - Without Annotations


![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/9f7feb9d-ceed-4835-849a-af81755edce4)


Description: This wireframe represents the dashboard of the Manager where the workload of employees would be displayed by employee shifts. The top 3 employees with the least workload and all the staff with a workload of over 40 hours per week would also be displayed in the Dashboard.



Employee Dashboard - With Annotations

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/f0ed9651-138b-4651-a36b-306c2c6f59df)


Employee Dashboard - Without Annotations

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/7b1da04a-4b8a-4f5c-a388-8f8cb9f11b53)



Description: This wireframe represents the dashboard of the Employee where the workload of the employee will be displayed via a calendar, by week or by month. The percentage of how many allocated jobs contained the employee's preferred instrument and preferred timing is also shown.


Employee Job Allocation - With Annotations

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/aad14215-4c3c-4212-ac19-309d366d1ebc)


Employee Job Allocation - Without Annotations

![Image](https://github.com/BenjaminTham-SIT/INF2001_P4-5/assets/111504470/0e922bda-245c-4e28-b5d8-aecdedb284df)


Description: This wireframe represents the Job Allocation page of the Employee. The Job Allocation page has 3 sub pages, one for the employee's allocated jobs, one for the employee's job availabilities and another for their preferences. This wireframe shows the sub page for the employee's allocated jobs.

____________________________________________________________________________________________________________________________
### Repository Commit status:

No commit 
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)

21/09/2023 - Completed Company Logo, Employee Dashboard
22/09/2023 - Completed Colour Palette, Employee Job Allocation
23/09/2023 - Completed Manager Job Allocation, Edited Employee Dashboard and Employee Job Allocation pages
Add Annotations and description for Wireframes
Edited and Completed "Font Style and Size" section of Design and Branding
____________________________________________________________________________________________________________________________

### Start Date - End Date:

21 September 2023 - 23 September 2023
