### ISSUE TITLE
[1.6.1] M1 Report Draft 1: Introduction

### ISSUE THREAD

**Issue by 2202528** [BenjaminTham-SIT/INF2001_P4-5#74]
### About:
M1 report introduction section is a brief introduction to our project. it gives the intended purpose of project, impact of the project and a brief overview of the sections that will be identified within the project.
____________________________________________________________________________________________________________________________
### Goals:
- plan a concise introduction
- complete writing an introduction
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] purpose paragraph
- [x] impact paragraph 
- [x] what to expect paragraph 
- [x] product scope section 
- [x] related background literature section
- [x] intended audience and document overview section
- [x] references and acknowledgement section

____________________________________________________________________________________________________________________________
### Allocated Time:
4 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
20/9 - 23/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by 2202528** [comment]
### Work Done

Wrote about Purpose of Project, the Impact paragraph, What to Expect, the Goal Paragraph and the related Background Literature as well as References

____________________________________________________________________________________________________________________________
### Repository Commit status:

No commit
____________________________________________________________________________________________________________________________
### Completion Deadline Effect:

____________________________________________________________________________________________________________________________
### Changelog:
____________________________________________________________________________________________________________________________
### Start Date - End Date:
20 September 2023 - 23 September

**Comment by Claire1202** [comment]
Work Done
Wrote about Product Scope and Intended Audience and Document Overview


Repository Commit status:
No commit

Completion Deadline Effect:

Changelog:
23/09/2023 - Completed product scope and intended audience and document overview 

Start Date - End Date:
20 September 2023 - 23 September
