### ISSUE TITLE
[2.1.1b] Lecture/Tutorial research 5/8

### ISSUE THREAD

**Issue by itsalys** [BenjaminTham-SIT/INF2001_P4-5#77]
### About:
Understanding of lecture materials relating to milestone 2. 
Group effort, Alyssa in charge of reading materials.
____________________________________________________________________________________________________________________________
### Goals:
- understand all topics and lecture from 5 - 8
- understand the relation between lecture and milestone 2
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] understand lecture 5
- [x] understand lecture 6
- [x] understand lecture 8
- [x] watch past lecture 5
- [x] watch past lecture 6
- [x] watch past lecture 8

____________________________________________________________________________________________________________________________
### Allocated Time:
 5 days
____________________________________________________________________________________________________________________________
### Start date - End Date:
25/9 - 29/9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [x] Benjamin
- [x] Claire
- [x] Claris
- [x] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [x] In Progress
- [ ] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:

**Comment by itsalys** [comment]
### Work Done:
Completed Lecture 5,6 & 8

____________________________________________________________________________________________________________________________
### Repository Commit status:
no commit

____________________________________________________________________________________________________________________________
### Completion Deadline Effect:
Completed

____________________________________________________________________________________________________________________________
### Changelog:
[Day/Month/2023] - (details)
29/09/2023 - Completed Lecture 5,6 & 8


____________________________________________________________________________________________________________________________
### Start Date - End Date:
25/9 - 29/9
