### ISSUE TITLE
[2.1.2] General Project Setup

### ISSUE THREAD

**Issue by 2202528** [BenjaminTham-SIT/INF2001_P4-5#80]
### About:
General setup of certain project channels like google files and lucid charts.
____________________________________________________________________________________________________________________________
### Goals:
- setup common file sharing channels
- setup common tools
____________________________________________________________________________________________________________________________
### Success - Completion Details:

- [x] setup google file milestone 2
- [x] setup lucid chart milestone 2
- [x] setup figma milestone 2

____________________________________________________________________________________________________________________________
### Allocated Time:
 1 day
____________________________________________________________________________________________________________________________
### Start date - End Date:
25/9 - 25 /9
____________________________________________________________________________________________________________________________
### Person-in-charge:

- [ ] Benjamin
- [ ] Claire
- [ ] Claris
- [ ] Alyssa
- [x] Megan

____________________________________________________________________________________________________________________________
### Task Status:

- [ ] In Progress
- [x] Complete 
- [ ] Incomplete 

____________________________________________________________________________________________________________________________
### Priority:

- [x] High Priority 
- [ ] Medium Priority 
- [ ] Low Priority

____________________________________________________________________________________________________________________________
### Notes:
